export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const ADDITION  = "ADDITION";
export const SUBSTRACTION = "SUBSTRACTION";
export const STORECOUNTER = "STORECOUNTER";
export const DELETECOUNTER = "DELETECOUNTER";
